
# Site settings
title: Yan Huang
name: Yan Huang
subtitle: Financial Economist
email: yhuang@nlpr.ia.ac.cn
description: >
  Financial Economist
baseurl: ""
url: "https://yanrockhuang.github.io/"
github_username:  yanrockhuang
disqus_baseurl: "https://yanrockhuang.github.io/"
disqus_shortname: https-yanrockhuang-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yan Huang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag


